#define BRICK_PTR_IMAGE_SET 0
#define BRICK_PTR_IMAGE_BINDING 0
#define RESULT_IMAGE_SET 0
#define RESULT_IMAGE_BINDING 1
#define COLOR_IMAGE_SET 0
#define COLOR_IMAGE_BINDING 2
#define BIN_VIS_IMAGE_SET 0
#define BIN_VIS_IMAGE_BINDING 3

#define BRICK_VOLUME_WIDTH_CONST_ID 0
#define BRICK_VOLUME_HEIGHT_CONST_ID 1
#define BRICK_VOLUME_DEPTH_CONST_ID 2
#define VOXEL_GRID_WIDTH_CONST_ID 3
#define VOXEL_GRID_HEIGHT_CONST_ID 4
#define VOXEL_GRID_DEPTH_CONST_ID 5
#define VOXEL_SCALE_CONST_ID 6
#define BIN_VIS_BRICK_SIZE_CONST_ID 7
#define COLOR_BRICK_SIZE_CONST_ID 8
#define WIDTH_CONST_ID 9
#define HEIGHT_CONST_ID 10
#define TEXEL_WIDTH_CONST_ID 11
#define TEXEL_HEIGHT_CONST_ID 12

struct PushConsts
{
	mat4 invViewProjection;
	ivec3 gridOffset;
};