#define RESULT_IMAGE_SET 0
#define RESULT_IMAGE_BINDING 0
#define DEPTH_IMAGE_SET 0
#define DEPTH_IMAGE_BINDING 1
#define SHADOW_IMAGE_SET 0
#define SHADOW_IMAGE_BINDING 2
#define SHADOW_SAMPLER_SET 0
#define SHADOW_SAMPLER_BINDING 3
#define POINT_SAMPLER_SET 0
#define POINT_SAMPLER_BINDING 4
#define SHADOW_MATRICES_SET 0
#define SHADOW_MATRICES_BINDING 5
#define TANGENT_SPACE_IMAGE_SET 0
#define TANGENT_SPACE_IMAGE_BINDING 6
#define CASCADE_PARAMS_BUFFER_SET 0
#define CASCADE_PARAMS_BUFFER_BINDING 7

#define CASCADE_COUNT_CONST_ID 0
#define WIDTH_CONST_ID 1
#define HEIGHT_CONST_ID 2
#define TEXEL_WIDTH_CONST_ID 3
#define TEXEL_HEIGHT_CONST_ID 4

struct PushConsts
{
	mat4 invViewMatrix;
	vec4 unprojectParams;
	vec3 direction;
	int cascadeDataOffset;
	int cascadeCount;
};