#define INSTANCE_DATA_SET 0
#define INSTANCE_DATA_BINDING 0
#define TRANSFORM_DATA_SET 0
#define TRANSFORM_DATA_BINDING 1
#define MATERIAL_DATA_SET 0
#define MATERIAL_DATA_BINDING 2
#define VERTEX_POSITIONS_SET 0
#define VERTEX_POSITIONS_BINDING 3
#define VERTEX_NORMALS_SET 0
#define VERTEX_NORMALS_BINDING 4
#define VERTEX_TEXCOORDS_SET 0
#define VERTEX_TEXCOORDS_BINDING 5
#define SUB_MESH_DATA_SET 0
#define SUB_MESH_DATA_BINDING 6
#define DEFERRED_SHADOW_IMAGE_SET 0
#define DEFERRED_SHADOW_IMAGE_BINDING 7
#define DIRECTIONAL_LIGHT_DATA_SET 0
#define DIRECTIONAL_LIGHT_DATA_BINDING 8
#define POINT_LIGHT_DATA_SET 0
#define POINT_LIGHT_DATA_BINDING 9
#define POINT_LIGHT_Z_BINS_SET 0
#define POINT_LIGHT_Z_BINS_BINDING 10
#define POINT_LIGHT_MASK_SET 0
#define POINT_LIGHT_MASK_BINDING 11
#define POINT_SAMPLER_SET 0
#define POINT_SAMPLER_BINDING 12
#define VOLUMETRIC_FOG_IMAGE_SET 0
#define VOLUMETRIC_FOG_IMAGE_BINDING 13
#define SSAO_IMAGE_SET 0
#define SSAO_IMAGE_BINDING 14
#define SPOT_LIGHT_DATA_SET 0
#define SPOT_LIGHT_DATA_BINDING 15
#define SPOT_LIGHT_Z_BINS_SET 0
#define SPOT_LIGHT_Z_BINS_BINDING 16
#define SPOT_LIGHT_MASK_SET 0
#define SPOT_LIGHT_MASK_BINDING 17

#define TEXTURES_SET 1
#define TEXTURES_BINDING 0
#define SAMPLERS_SET 1
#define SAMPLERS_BINDING 1

#define DIRECTIONAL_LIGHT_COUNT_CONST_ID 0
#define WIDTH_CONST_ID 1
#define HEIGHT_CONST_ID 2
#define TEXEL_WIDTH_CONST_ID 3
#define TEXEL_HEIGHT_CONST_ID 4

#define OUT_RESULT 0
#define OUT_NORMAL 1
#define OUT_SPECULAR_ROUGHNESS 2

struct PushConsts
{
	mat4 jitteredViewProjectionMatrix;
	vec4 viewMatrixRow0;
	vec4 viewMatrixRow1;
	vec4 viewMatrixRow2;
	uint pointLightCount;
	uint transformIndex;
	uint materialIndex;
	uint ambientOcclusion;
};