#define RESULT_IMAGE_SET 0
#define RESULT_IMAGE_BINDING 0
#define DEPTH_IMAGE_SET 0
#define DEPTH_IMAGE_BINDING 1
#define ALBEDO_IMAGE_SET 0
#define ALBEDO_IMAGE_BINDING 2
#define NORMAL_IMAGE_SET 0
#define NORMAL_IMAGE_BINDING 3
#define IRRADIANCE_VOLUME_IMAGE_SET 0
#define IRRADIANCE_VOLUME_IMAGE_BINDING 4
#define IRRADIANCE_VOLUME_DEPTH_IMAGE_SET 0
#define IRRADIANCE_VOLUME_DEPTH_IMAGE_BINDING 5
#define OCCLUSION_IMAGE_SET 0
#define OCCLUSION_IMAGE_BINDING 6


#define WIDTH_CONST_ID 0
#define HEIGHT_CONST_ID 1
#define TEXEL_WIDTH_CONST_ID 2
#define TEXEL_HEIGHT_CONST_ID 3
#define IRRADIANCE_VOLUME_WIDTH_CONST_ID 4
#define IRRADIANCE_VOLUME_HEIGHT_CONST_ID 5
#define IRRADIANCE_VOLUME_DEPTH_CONST_ID 6
#define IRRADIANCE_VOLUME_CASCADES_CONST_ID 7
#define IRRADIANCE_VOLUME_BASE_SCALE_CONST_ID 8
#define IRRADIANCE_VOLUME_PROBE_SIDE_LENGTH_CONST_ID 9
#define IRRADIANCE_VOLUME_DEPTH_PROBE_SIDE_LENGTH_CONST_ID 10

struct PushConsts
{
	vec4 unprojectParams;
	vec4 invViewMatrixRow0;
	vec4 invViewMatrixRow1;
	vec4 invViewMatrixRow2;
};