#define AGE_IMAGE_SET 0
#define AGE_IMAGE_BINDING 0
#define QUEUE_BUFFER_SET 0
#define QUEUE_BUFFER_BINDING 1
#define IRRADIANCE_VOLUME_IMAGE_SET 0
#define IRRADIANCE_VOLUME_IMAGE_BINDING 2
#define VOXEL_IMAGE_SET 0
#define VOXEL_IMAGE_BINDING 3

#define GRID_WIDTH_CONST_ID 0
#define GRID_HEIGHT_CONST_ID 1
#define GRID_DEPTH_CONST_ID 2
#define CASCADES_CONST_ID 3
#define GRID_BASE_SCALE_CONST_ID 4
#define VOXEL_GRID_WIDTH_CONST_ID 5
#define VOXEL_GRID_HEIGHT_CONST_ID 6
#define VOXEL_GRID_DEPTH_CONST_ID 7
#define VOXEL_CASCADES_CONST_ID 8
#define VOXEL_BASE_SCALE_CONST_ID 9
#define QUEUE_CAPACITY_CONST_ID 10

struct PushConsts
{
	vec4 cameraPosition;
	float time;
};