#define RESULT_IMAGE_SET 0
#define RESULT_IMAGE_BINDING 0
#define DEPTH_IMAGE_SET 0
#define DEPTH_IMAGE_BINDING 1
#define UV_IMAGE_SET 0
#define UV_IMAGE_BINDING 2
#define DDXY_LENGTH_IMAGE_SET 0
#define DDXY_LENGTH_IMAGE_BINDING 3
#define DDXY_ROT_MATERIAL_ID_IMAGE_SET 0
#define DDXY_ROT_MATERIAL_ID_IMAGE_BINDING 4
#define TANGENT_SPACE_IMAGE_SET 0
#define TANGENT_SPACE_IMAGE_BINDING 5
#define DEFERRED_SHADOW_IMAGE_SET 0
#define DEFERRED_SHADOW_IMAGE_BINDING 6
#define DIRECTIONAL_LIGHT_DATA_SET 0
#define DIRECTIONAL_LIGHT_DATA_BINDING 7
#define POINT_LIGHT_DATA_SET 0
#define POINT_LIGHT_DATA_BINDING 8
#define POINT_LIGHT_Z_BINS_SET 0
#define POINT_LIGHT_Z_BINS_BINDING 9
#define POINT_LIGHT_MASK_SET 0
#define POINT_LIGHT_MASK_BINDING 10
#define MATERIAL_DATA_SET 0
#define MATERIAL_DATA_BINDING 11
#define ALBEDO_IMAGE_SET 0
#define ALBEDO_IMAGE_BINDING 12
#define NORMAL_IMAGE_SET 0
#define NORMAL_IMAGE_BINDING 13

#define TEXTURES_SET 1
#define TEXTURES_BINDING 0
#define SAMPLERS_SET 1
#define SAMPLERS_BINDING 1

#define DIRECTIONAL_LIGHT_COUNT_CONST_ID 0
#define WIDTH_CONST_ID 1
#define HEIGHT_CONST_ID 2
#define TEXEL_WIDTH_CONST_ID 3
#define TEXEL_HEIGHT_CONST_ID 4

struct PushConsts
{
	vec4 unprojectParams;
	uint pointLightCount;
};