#define QUEUE_BUFFER_SET 0
#define QUEUE_BUFFER_BINDING 0
#define PREV_QUEUE_BUFFER_SET 0
#define PREV_QUEUE_BUFFER_BINDING 1
#define INDIRECT_CMD_SET 0
#define INDIRECT_CMD_BINDING 2

#define QUEUE_CAPACITY_CONST_ID 0