#define BRICK_PTR_IMAGE_SET 0
#define BRICK_PTR_IMAGE_BINDING 0
#define FREE_BRICKS_BUFFER_SET 0
#define FREE_BRICKS_BUFFER_BINDING 1
#define MARK_IMAGE_SET 0
#define MARK_IMAGE_BINDING 2


#define BRICK_VOLUME_WIDTH_CONST_ID 0
#define BRICK_VOLUME_HEIGHT_CONST_ID 1
#define BRICK_VOLUME_DEPTH_CONST_ID 2