#define INSTANCE_DATA_SET 0
#define INSTANCE_DATA_BINDING 0
#define TRANSFORM_DATA_SET 0
#define TRANSFORM_DATA_BINDING 1
#define MATERIAL_DATA_SET 0
#define MATERIAL_DATA_BINDING 2
#define VERTEX_POSITIONS_SET 0
#define VERTEX_POSITIONS_BINDING 3
#define VERTEX_NORMALS_SET 0
#define VERTEX_NORMALS_BINDING 4
#define VERTEX_TEXCOORDS_SET 0
#define VERTEX_TEXCOORDS_BINDING 5
#define SUB_MESH_DATA_SET 0
#define SUB_MESH_DATA_BINDING 6
#define VOXEL_IMAGE_SET 0
#define VOXEL_IMAGE_BINDING 7
#define OPACITY_IMAGE_SET 0
#define OPACITY_IMAGE_BINDING 8
#define SHADOW_IMAGE_SET 0
#define SHADOW_IMAGE_BINDING 9
#define SHADOW_SAMPLER_SET 0
#define SHADOW_SAMPLER_BINDING 10
#define DIRECTIONAL_LIGHT_DATA_SET 0
#define DIRECTIONAL_LIGHT_DATA_BINDING 11
#define SHADOW_MATRICES_SET 0
#define SHADOW_MATRICES_BINDING 12
#define IRRADIANCE_VOLUME_IMAGE_SET 0
#define IRRADIANCE_VOLUME_IMAGE_BINDING 13

#define TEXTURES_SET 1
#define TEXTURES_BINDING 0
#define SAMPLERS_SET 1
#define SAMPLERS_BINDING 1

#define DIRECTIONAL_LIGHT_COUNT_CONST_ID 0
#define VOXEL_GRID_WIDTH_CONST_ID 1
#define VOXEL_GRID_HEIGHT_CONST_ID 2
#define VOXEL_GRID_DEPTH_CONST_ID 3
#define IRRADIANCE_VOLUME_WIDTH_CONST_ID 4
#define IRRADIANCE_VOLUME_HEIGHT_CONST_ID 5
#define IRRADIANCE_VOLUME_DEPTH_CONST_ID 6
#define IRRADIANCE_VOLUME_CASCADES_CONST_ID 7
#define IRRADIANCE_VOLUME_BASE_SCALE_CONST_ID 8

struct PushConsts
{
	mat4 invViewMatrix;
	vec3 gridOffset;
	float voxelScale;
	float invGridResolution;
	uint cascade;
	uint superSamplingFactor;
	uint transformIndex;
	uint materialIndex;
};