#define INSTANCE_DATA_SET 0
#define INSTANCE_DATA_BINDING 0
#define TRANSFORM_DATA_SET 0
#define TRANSFORM_DATA_BINDING 1
#define MATERIAL_DATA_SET 0
#define MATERIAL_DATA_BINDING 2
#define VERTEX_POSITIONS_SET 0
#define VERTEX_POSITIONS_BINDING 3
#define VERTEX_NORMALS_SET 0
#define VERTEX_NORMALS_BINDING 4
#define VERTEX_TEXCOORDS_SET 0
#define VERTEX_TEXCOORDS_BINDING 5
#define SUB_MESH_DATA_SET 0
#define SUB_MESH_DATA_BINDING 6
#define BRICK_PTR_IMAGE_SET 0
#define BRICK_PTR_IMAGE_BINDING 7
#define BIN_VIS_IMAGE_BUFFER_SET 0
#define BIN_VIS_IMAGE_BUFFER_BINDING 8
#define SHADOW_IMAGE_SET 0
#define SHADOW_IMAGE_BINDING 9
#define SHADOW_SAMPLER_SET 0
#define SHADOW_SAMPLER_BINDING 10
#define DIRECTIONAL_LIGHT_DATA_SET 0
#define DIRECTIONAL_LIGHT_DATA_BINDING 11
#define SHADOW_MATRICES_SET 0
#define SHADOW_MATRICES_BINDING 12
#define COLOR_IMAGE_BUFFER_SET 0
#define COLOR_IMAGE_BUFFER_BINDING 13
#define IRRADIANCE_VOLUME_IMAGE_SET 0
#define IRRADIANCE_VOLUME_IMAGE_BINDING 14
#define IRRADIANCE_VOLUME_DEPTH_IMAGE_SET 0
#define IRRADIANCE_VOLUME_DEPTH_IMAGE_BINDING 15

#define TEXTURES_SET 1
#define TEXTURES_BINDING 0
#define SAMPLERS_SET 1
#define SAMPLERS_BINDING 1

#define DIRECTIONAL_LIGHT_COUNT_CONST_ID 0
#define BRICK_VOLUME_WIDTH_CONST_ID 1
#define BRICK_VOLUME_HEIGHT_CONST_ID 2
#define BRICK_VOLUME_DEPTH_CONST_ID 3
#define INV_VOXEL_BRICK_SIZE_CONST_ID 4
#define VOXEL_SCALE_CONST_ID 5
#define BRICK_SCALE_CONST_ID 6
#define BIN_VIS_BRICK_SIZE_CONST_ID 7
#define COLOR_BRICK_SIZE_CONST_ID 8
#define IRRADIANCE_VOLUME_WIDTH_CONST_ID 9
#define IRRADIANCE_VOLUME_HEIGHT_CONST_ID 10
#define IRRADIANCE_VOLUME_DEPTH_CONST_ID 11
#define IRRADIANCE_VOLUME_CASCADES_CONST_ID 12
#define IRRADIANCE_VOLUME_BASE_SCALE_CONST_ID 13
#define IRRADIANCE_VOLUME_PROBE_SIDE_LENGTH_CONST_ID 14
#define IRRADIANCE_VOLUME_DEPTH_PROBE_SIDE_LENGTH_CONST_ID 15

struct PushConsts
{
	mat4 invViewMatrix;
	vec3 gridOffset;
	float invGridResolution;
	uint superSamplingFactor;
	uint transformIndex;
	uint materialIndex;
};