#define VOXEL_PTR_IMAGE_SET 0
#define VOXEL_PTR_IMAGE_BINDING 0
#define FREE_BRICKS_BUFFER_SET 0
#define FREE_BRICKS_BUFFER_BINDING 1
#define MARK_IMAGE_SET 0
#define MARK_IMAGE_BINDING 2


#define VOXEL_GRID_WIDTH_CONST_ID 0
#define VOXEL_GRID_HEIGHT_CONST_ID 1
#define VOXEL_GRID_DEPTH_CONST_ID 2